name: Zip a new Version

on:
  workflow_dispatch:

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: *.toc *.lua *.xml
          dest: whoaCharacterStats.zip
