name: Zip a new Version

on:
  workflow_dispatch:

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: whoaCharacterStats.toc config.lua settings.lua whoaCharacterStats.lua bindings.xml
          dest: whoaCharacterStats.zip
      - uses: actions/upload-artifact@v1
        with:
          name: latest-version
          path: ${{ github.workspace }}/whoaCharacterStats.zip
